"""Database engine, session, and SQLAlchemy declarative base.

Conventions:
* All ORM models inherit from :class:`Base`.
* Every business table inherits from :class:`Timestamped` and (where applicable)
  :class:`Versioned` and :class:`SoftDeletable`.
* The async session is the **only** path application code uses to talk to the
  database. Sync session is exposed only for Alembic.
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncGenerator
from datetime import datetime

from sqlalchemy import DateTime, Integer, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.config import settings

# --- Naming conventions ensure deterministic constraint names across envs ---
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s__%(column_0_name)s",
    "ck": "ck_%(table_name)s__%(constraint_name)s",
    "fk": "fk_%(table_name)s__%(column_0_name)s__%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Declarative base for all NHPMBR ORM models."""

    metadata = metadata


# --- Engine / session factory ---
# NullPool is fine for serverless; for long-running ASGI workers a real pool
# is faster. We size conservatively and let env override.
engine = create_async_engine(
    str(settings.database_url),
    pool_pre_ping=True,
    pool_size=10,
    max_overflow=10,
    pool_recycle=1800,
    future=True,
    echo=False,
)

AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    expire_on_commit=False,
    class_=AsyncSession,
)


async def get_session() -> AsyncGenerator[AsyncSession, None]:
    """FastAPI dependency yielding a transactional session.

    A single session per request. We do *not* auto-commit; the route or service
    decides when to commit, but we always close.
    """
    async with AsyncSessionLocal() as session:
        try:
            yield session
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


# ----- Reusable mixins -----


class IdMixin:
    """UUIDv7 primary key generated by the database (see init SQL)."""

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("uuid_generate_v7()"),
    )


class Timestamped:
    """``created_at`` and ``updated_at`` columns, server-managed."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class Versioned:
    """Optimistic-concurrency version column. Bumped via DB trigger or app code."""

    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, server_default="1")


class SoftDeletable:
    """``deleted_at`` for soft delete; filtered out by RLS or repo queries."""

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


async def set_request_user_id(session: AsyncSession, user_id: uuid.UUID | None) -> None:
    """Bind the current user to the DB session for RLS predicates.

    Row-level-security policies read ``current_setting('app.current_user_id')``.
    Call this immediately after acquiring a session in a request scope.
    """
    if user_id is None:
        await session.execute(text("SELECT set_config('app.current_user_id', '', true)"))
    else:
        await session.execute(
            text("SELECT set_config('app.current_user_id', :uid, true)"),
            {"uid": str(user_id)},
        )
